#!/bin/sh
#First install npm and then uglify-es (npm install uglify-es -g)
cd ../sources/web
uglifyjs map-input-widget.js -c  -o map-input-widget.min.js
uglifyjs map-input-widget.css -c  -o map-input-widget.min.css